# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='New Note', max_length=50)),
                ('description', models.CharField(blank=True, default='md-yellow-200-bg', max_length=200)),
                ('archive', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='static/')),
                ('color', models.CharField(blank='false', choices=[('Red', 'md-red-200-bg'), ('Pink', 'md-pink-200-bg'), ('Purple', 'md-purple-200-bg'), ('Deep Purple', 'md-deep-purple-200-bg'), ('Indigo', 'md-indigo-200-bg'), ('Blue', 'md-blue-200-bg'), ('Light-Blue', 'md-light-blue-200-bg'), ('Cyan', 'md-cyan-200-bg'), ('Teal', 'md-teal-200-bg'), ('Green', 'md-green-200-bg'), ('Light-Green', 'md-light-green-200-bg'), ('Lime', 'md-lime-200-bg'), ('Yellow', 'md-yellow-200-bg'), ('Amber', 'md-amber-200-bg'), ('Orange', 'md-orange-200-bg'), ('Deep-Orange', 'md-deep-orange-200-bg'), ('Brown', 'md-brown-200-bg'), ('Grey', 'md-grey-200-bg'), ('Blue-Grey', 'md-blue-grey-200-bg')], default='', max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='cininotes.Note'),
        ),
    ]
