# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField()),
                ('start_date', models.DateTimeField(blank=True)),
                ('due_date', models.DateTimeField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='untitled', max_length=100)),
                ('label', models.CharField(choices=[('c1', '#388E3C'), ('c2', '#FF9800'), ('c3', '#F44336'), ('c4', '#9C27B0'), ('c5', '#0091EA'), ('c6', '#F44336')], default='#0091EA', max_length=30)),
                ('color', models.CharField(choices=[('issue', 'Issue'), ('frontend', 'Frontend'), ('api', 'API'), ('backend', 'Backend'), ('mobile', 'Mobile')], default='Backend', max_length=30)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.ToDoItem')),
            ],
        ),
    ]
