# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='New Note', max_length=50)),
                ('uri', models.CharField(blank=True, default='New Note', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='New Card', max_length=50)),
                ('description', models.CharField(blank=True, default='No description given.', max_length=250)),
                ('subscribed', models.BooleanField(default=True)),
                ('check_items', models.IntegerField()),
                ('check_items_checked', models.IntegerField()),
                ('due', models.DateTimeField(blank=True)),
                ('board_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='ciniscrum.ScrumBoard')),
            ],
        ),
        migrations.CreateModel(
            name='ScrumLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, default='New Note', max_length=50)),
                ('name', models.CharField(blank=True, default='New Note', max_length=50)),
                ('color', models.CharField(blank=True, default='New Note', max_length=50)),
                ('board_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='ciniscrum.ScrumBoard')),
            ],
        ),
        migrations.CreateModel(
            name='ScrumList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Django Application', max_length=50)),
                ('board_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='ciniscrum.ScrumBoard')),
            ],
        ),
        migrations.CreateModel(
            name='ScrumMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='New Card', max_length=50)),
                ('avatar', models.CharField(blank=True, default='New Card', max_length=50)),
                ('board_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ciniscrum.ScrumBoard')),
            ],
        ),
        migrations.CreateModel(
            name='ScrumSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='blue-grey', max_length=50)),
                ('card_cover_images', models.BooleanField(default=False)),
                ('subscribed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='scrumboard',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='ciniscrum.ScrumSettings'),
        ),
    ]
